spring.application.name=arts

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/art_treasure
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


#Additional native properties to set on the JPA provider.
spring.jpa.properties.hibernate.format_sql=true

# Gmail
# Gmail SMTP Configuration for Non-2FA Users
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${YOUR_MAIL}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
email.from-address=${YOUR_MAIL}