spring.application.name=arts

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/art_treasure
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:Shakeer@123}


#Additional native properties to set on the JPA provider.
spring.jpa.properties.hibernate.format_sql=true

# Gmail
# Gmail SMTP Configuration for Non-2FA Users
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2402.sgrvt@gmail.com
spring.mail.password=${MAIL_PASSWORD:xzzp wujf hnah ogwi}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
email.from-address=2402.sgrvt@gmail.com